
agent:
    discount_gamma: 0.99
    soft_update_tau: 0.05 # for encoder
    gae_lambda: 0.97
    clip_ratio_eps: 0.2
    dual_clip_ratio: 3.0
    max_grad_norm: 0.5
    entropy_coef: 0.0
    obs_normalizer: MeanStdNormalizer

network:
    z_dim: 64
    actor_lr: 0.0003
    critic_lr: 0.001
    encoder_lr: 0.0003
    actor_hidden_dim: [256, 256]
    encoder_hidden_dim: [256, 256]
    r_critic_hidden_dim: [256, 256]
    c_critic_hidden_dim: [256, 256]
    discrete_n_buckets: 63 # discrete regression
    discrete_range: [-2.0, 4.0]
    repr_type: "FCSRL"

env:
    name: "SafetyPointGoal1Gymnasium-v0"
    num_env_train: 8 
    num_env_test: 10
    max_episode_len: 1000

trainer:
    replay_size: 50000
    warmup_episode: 16
    epoch: 25
    step_per_epoch: 2500
    collect_episode_per_step: 32
    train_repeat: 2
    batch_size: 64

    test_episode: 10

    writer_dir: "exp/log"
    model_dir: "exp/model"

Lagrangian:
    init_lagrg: 0.0
    KP: 0.02
    KI: 0.005
    KD: 0.01
    max_lambda: &MAX_LAMBDA 1.0
    constraint_threshold: &CONSTRAINT_THRESHOLD 25
    update_by_J: True  # else update by E[q_c]
    schedule_threshold: False
    threshold_start: 200
    threshold_end: *CONSTRAINT_THRESHOLD
    schedule_epoch: 5

misc:
    seed: 100
    cudaid: -1
    render: 0.0
    test: False